routes:
    - route: "^.+\\.(js|css|svg|ttf)$"
      #  cache static assets for 1 year
      headers:
         Cache-Control: "max-age=31557600, no-transform, public"
      gzip: true
    - route: "^.+\\.(png|jpg)$"
      headers:
         Cache-Control: "max-age=31557600, no-transform, public"
      gzip: false
    - route: "^.+\\.(html|xml|json)$"
      gzip: true   
